# docker-compose file for development setup
version: "3"
services:
  worker:
    build:
      context: ./app
      dockerfile: Dockerfile_worker
    command: python3 run_worker.py
    container_name: worker
    networks:
      - tension_analysis_dev
    restart: always
    volumes:
      - results_storage:/mnt/tension_analysis_results
      - ./app:/srv/app
      - ./data:/srv/data
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - app
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-facility: local2
    ports:
      - "5000:80"  # Final port exposed to host
    restart: always
    volumes:
      - ./app/static:/var/www/static
      - unix_socket:/var/run/unix_socket
  app:
    build: ./app
    command: uwsgi -s /var/run/unix_socket/tension_analysis.sock --manage-script-name --mount /=tension_analysis:create_app()
    container_name: app
    depends_on:
      - stanford_corenlp
      - cron
    networks:
      - tension_analysis_dev
    restart: always
    volumes:
      - ./app:/srv/app
      - ./data:/srv/data
      - results_storage:/mnt/tension_analysis_results
      - unix_socket:/var/run/unix_socket
  cron:
    build: ./cron
    container_name: cron
    restart: always
    volumes:
      - results_storage:/mnt/storage
  stanford_corenlp:
    build: ./stanford_corenlp
    container_name: stanford_corenlp
    expose:
      - "9999"
    logging:
      driver: syslog
      options:
        syslog-address: "udp://127.0.0.1:514"
        syslog-facility: local2
    networks:
      - tension_analysis_dev
    restart: always
networks:
  tension_analysis_dev:
volumes:
  results_storage:
  unix_socket: